// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"sync"
)

// ClaudeCommandRunnerMock is a mock implementation of executor.ClaudeCommandRunner.
//
//	func TestSomethingThatUsesClaudeCommandRunner(t *testing.T) {
//
//		// make and configure a mocked executor.ClaudeCommandRunner
//		mockedClaudeCommandRunner := &ClaudeCommandRunnerMock{
//			RunFunc: func(ctx context.Context, name string, args ...string) (io.Reader, func() error, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedClaudeCommandRunner in code that requires executor.ClaudeCommandRunner
//		// and then make assertions.
//
//	}
type ClaudeCommandRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, name string, args ...string) (io.Reader, func() error, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *ClaudeCommandRunnerMock) Run(ctx context.Context, name string, args ...string) (io.Reader, func() error, error) {
	if mock.RunFunc == nil {
		panic("ClaudeCommandRunnerMock.RunFunc: method is nil but ClaudeCommandRunner.Run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Args []string
	}{
		Ctx:  ctx,
		Name: name,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, name, args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedClaudeCommandRunner.RunCalls())
func (mock *ClaudeCommandRunnerMock) RunCalls() []struct {
	Ctx  context.Context
	Name string
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
