// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// LoggerMock is a mock implementation of git.Logger.
//
//	func TestSomethingThatUsesLogger(t *testing.T) {
//
//		// make and configure a mocked git.Logger
//		mockedLogger := &LoggerMock{
//			PrintfFunc: func(format string, args ...any) (int, error) {
//				panic("mock out the Printf method")
//			},
//		}
//
//		// use mockedLogger in code that requires git.Logger
//		// and then make assertions.
//
//	}
type LoggerMock struct {
	// PrintfFunc mocks the Printf method.
	PrintfFunc func(format string, args ...any) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Printf holds details about calls to the Printf method.
		Printf []struct {
			// Format is the format argument value.
			Format string
			// Args is the args argument value.
			Args []any
		}
	}
	lockPrintf sync.RWMutex
}

// Printf calls PrintfFunc.
func (mock *LoggerMock) Printf(format string, args ...any) (int, error) {
	if mock.PrintfFunc == nil {
		panic("LoggerMock.PrintfFunc: method is nil but Logger.Printf was just called")
	}
	callInfo := struct {
		Format string
		Args   []any
	}{
		Format: format,
		Args:   args,
	}
	mock.lockPrintf.Lock()
	mock.calls.Printf = append(mock.calls.Printf, callInfo)
	mock.lockPrintf.Unlock()
	return mock.PrintfFunc(format, args...)
}

// PrintfCalls gets all the calls that were made to Printf.
// Check the length with:
//
//	len(mockedLogger.PrintfCalls())
func (mock *LoggerMock) PrintfCalls() []struct {
	Format string
	Args   []any
} {
	var calls []struct {
		Format string
		Args   []any
	}
	mock.lockPrintf.RLock()
	calls = mock.calls.Printf
	mock.lockPrintf.RUnlock()
	return calls
}
