// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// GitCheckerMock is a mock implementation of processor.GitChecker.
//
//	func TestSomethingThatUsesGitChecker(t *testing.T) {
//
//		// make and configure a mocked processor.GitChecker
//		mockedGitChecker := &GitCheckerMock{
//			HeadHashFunc: func() (string, error) {
//				panic("mock out the HeadHash method")
//			},
//		}
//
//		// use mockedGitChecker in code that requires processor.GitChecker
//		// and then make assertions.
//
//	}
type GitCheckerMock struct {
	// HeadHashFunc mocks the HeadHash method.
	HeadHashFunc func() (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// HeadHash holds details about calls to the HeadHash method.
		HeadHash []struct {
		}
	}
	lockHeadHash sync.RWMutex
}

// HeadHash calls HeadHashFunc.
func (mock *GitCheckerMock) HeadHash() (string, error) {
	if mock.HeadHashFunc == nil {
		panic("GitCheckerMock.HeadHashFunc: method is nil but GitChecker.HeadHash was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHeadHash.Lock()
	mock.calls.HeadHash = append(mock.calls.HeadHash, callInfo)
	mock.lockHeadHash.Unlock()
	return mock.HeadHashFunc()
}

// HeadHashCalls gets all the calls that were made to HeadHash.
// Check the length with:
//
//	len(mockedGitChecker.HeadHashCalls())
func (mock *GitCheckerMock) HeadHashCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHeadHash.RLock()
	calls = mock.calls.HeadHash
	mock.lockHeadHash.RUnlock()
	return calls
}
