// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// InputCollectorMock is a mock implementation of processor.InputCollector.
//
//	func TestSomethingThatUsesInputCollector(t *testing.T) {
//
//		// make and configure a mocked processor.InputCollector
//		mockedInputCollector := &InputCollectorMock{
//			AskDraftReviewFunc: func(ctx context.Context, question string, planContent string) (string, string, error) {
//				panic("mock out the AskDraftReview method")
//			},
//			AskQuestionFunc: func(ctx context.Context, question string, options []string) (string, error) {
//				panic("mock out the AskQuestion method")
//			},
//		}
//
//		// use mockedInputCollector in code that requires processor.InputCollector
//		// and then make assertions.
//
//	}
type InputCollectorMock struct {
	// AskDraftReviewFunc mocks the AskDraftReview method.
	AskDraftReviewFunc func(ctx context.Context, question string, planContent string) (string, string, error)

	// AskQuestionFunc mocks the AskQuestion method.
	AskQuestionFunc func(ctx context.Context, question string, options []string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// AskDraftReview holds details about calls to the AskDraftReview method.
		AskDraftReview []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Question is the question argument value.
			Question string
			// PlanContent is the planContent argument value.
			PlanContent string
		}
		// AskQuestion holds details about calls to the AskQuestion method.
		AskQuestion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Question is the question argument value.
			Question string
			// Options is the options argument value.
			Options []string
		}
	}
	lockAskDraftReview sync.RWMutex
	lockAskQuestion    sync.RWMutex
}

// AskDraftReview calls AskDraftReviewFunc.
func (mock *InputCollectorMock) AskDraftReview(ctx context.Context, question string, planContent string) (string, string, error) {
	if mock.AskDraftReviewFunc == nil {
		panic("InputCollectorMock.AskDraftReviewFunc: method is nil but InputCollector.AskDraftReview was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Question    string
		PlanContent string
	}{
		Ctx:         ctx,
		Question:    question,
		PlanContent: planContent,
	}
	mock.lockAskDraftReview.Lock()
	mock.calls.AskDraftReview = append(mock.calls.AskDraftReview, callInfo)
	mock.lockAskDraftReview.Unlock()
	return mock.AskDraftReviewFunc(ctx, question, planContent)
}

// AskDraftReviewCalls gets all the calls that were made to AskDraftReview.
// Check the length with:
//
//	len(mockedInputCollector.AskDraftReviewCalls())
func (mock *InputCollectorMock) AskDraftReviewCalls() []struct {
	Ctx         context.Context
	Question    string
	PlanContent string
} {
	var calls []struct {
		Ctx         context.Context
		Question    string
		PlanContent string
	}
	mock.lockAskDraftReview.RLock()
	calls = mock.calls.AskDraftReview
	mock.lockAskDraftReview.RUnlock()
	return calls
}

// AskQuestion calls AskQuestionFunc.
func (mock *InputCollectorMock) AskQuestion(ctx context.Context, question string, options []string) (string, error) {
	if mock.AskQuestionFunc == nil {
		panic("InputCollectorMock.AskQuestionFunc: method is nil but InputCollector.AskQuestion was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Question string
		Options  []string
	}{
		Ctx:      ctx,
		Question: question,
		Options:  options,
	}
	mock.lockAskQuestion.Lock()
	mock.calls.AskQuestion = append(mock.calls.AskQuestion, callInfo)
	mock.lockAskQuestion.Unlock()
	return mock.AskQuestionFunc(ctx, question, options)
}

// AskQuestionCalls gets all the calls that were made to AskQuestion.
// Check the length with:
//
//	len(mockedInputCollector.AskQuestionCalls())
func (mock *InputCollectorMock) AskQuestionCalls() []struct {
	Ctx      context.Context
	Question string
	Options  []string
} {
	var calls []struct {
		Ctx      context.Context
		Question string
		Options  []string
	}
	mock.lockAskQuestion.RLock()
	calls = mock.calls.AskQuestion
	mock.lockAskQuestion.RUnlock()
	return calls
}
